feedhq/feeds/urls.py
from django.conf.urls import url, patterns

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.entries_list, name='home'),
    url(r'^(?P<page>\d+)/$', views.entries_list, name='home'),
    url(r'^unread/$', views.entries_list,
        {'only_unread': True}, name='unread'),
    url(r'^unread/(?P<page>\d+)/$', views.entries_list,
        {'only_unread': True}, name='unread'),

    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/unread/$', views.dashboard,
        {'only_unread': True}, name='unread_dashboard'),

    url(r'^stars/$', views.entries_list,
        {'starred': True}, name='stars'),

    url(r'^stars/(?P<page>\d+)/$', views.entries_list,
        {'starred': True}, name='stars'),

    url(r'^manage/$', views.manage, name='manage'),

    url(r'^import/$', views.import_feeds, name='import_feeds'),
    url(r'^subscribe/$', views.subscribe, name='subscribe'),
    url(r'^keyboard/$', views.keyboard, name='keyboard'),

    # Categories
    url(r'^category/add/$', views.add_category, name='add_category'),
    url(r'^category/(?P<slug>[\w_-]+)/edit/$', views.edit_category,
        name='edit_category'),
    url(r'^category/(?P<slug>[\w_-]+)/delete/$', views.delete_category,
        name='delete_category'),

    url(r'^category/(?P<category>[\w_-]+)/$', views.entries_list,
        name='category'),

    url(r'^category/(?P<category>[\w_-]+)/(?P<page>\d+)/$',
        views.entries_list, name='category'),

    url(r'^category/(?P<category>[\w_-]+)/unread/$', views.entries_list,
        {'only_unread': True}, name='unread_category'),
    url(r'^category/(?P<category>[\w_-]+)/unread/(?P<page>\d+)/$',
        views.entries_list, {'only_unread': True}, name='unread_category'),

    # Feeds
    url(r'^feed/add/$', views.add_feed, name='add_feed'),
    url(r'^feed/(?P<feed>\d+)/edit/$', views.edit_feed, name='edit_feed'),
    url(r'^feed/(?P<feed>\d+)/delete/$', views.delete_feed,
        name='delete_feed'),

    url(r'^feed/(?P<feed>\d+)/$', views.entries_list, name='feed'),
    url(r'^feed/(?P<feed>\d+)/(?P<page>\d+)/$', views.entries_list,
        name='feed'),
    url(r'^feed/(?P<feed>\d+)/unread/$', views.entries_list,
        {'only_unread': True}, name='unread_feed'),
    url(r'^feed/(?P<feed>\d+)/unread/(?P<page>\d+)/$', views.entries_list,
        {'only_unread': True}, name='unread_feed'),

    # Entries
    url(r'^entries/(?P<entry_id>\d+)/$', views.item, name='item'),
)

feedhq/profiles/urls.py
from django.conf.urls import url, patterns, include

from . import views

urlpatterns = patterns(
    '',
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^sharing/$', views.sharing, name='sharing'),
    url(r'^bookmarklet/$', views.bookmarklet, name='bookmarklet'),
    url(r'^password/$', views.password, name='password'),
    url(r'^export/$', views.export, name='export'),
    url(r'^readlater/(?P<service>readability|readitlater|instapaper|'
        r'pocket|wallabag|none)/$',
        views.services, name='services'),
    url(r'^readlater/pocket/return/$', views.pocket, name='pocket_return'),
    url(r'^readlater/$', views.read_later, name='read_later'),
    url(r'^destroy/$', views.destroy, name='destroy_account'),
    url(r'^destroy/sent/$', views.destroy_sent, name='destroy_sent'),
    url(r'^destroy/confirm/(?P<token>[^\/]+)/$',
        views.destroy_confirm, name='destroy_confirm'),
    url(r'^destroy/done/$', views.destroy_done, name='destroy_done'),
    url(r'^recover/$', views.recover, name='password_reset_recover'),
    url(r'^', include('password_reset.urls')),
)

feedhq/reader/urls.py
from django.conf.urls import patterns, url, include

from . import views


urlpatterns = patterns(
    '',
    url(r'^accounts/ClientLogin$', views.login, name='login'),
    url(r'^reader/api/0/', include('feedhq.reader.api_urls')),
    url(r'^reader/atom/(?P<content_id>.+)?$', views.stream_contents,
        {'output': 'atom'}, name='atom_contents'),

)

feedhq/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, patterns, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from ratelimitbackend import admin
admin.autodiscover()

from . import views
from .profiles.forms import AuthForm


urlpatterns = patterns(
    '',
    (r'^admin/rq/', include('django_rq_dashboard.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^subscriber/', include('django_push.subscriber.urls')),
    url(r'^robots.txt$', views.robots),
    url(r'^humans.txt$', views.humans),
    url(r'^favicon.ico$', views.favicon),
    url(r'^apple-touch-icon-precomposed.png$', views.touch_icon),
    url(r'^apple-touch-icon.png$', views.touch_icon),
    (r'^', include('feedhq.reader.urls', namespace='reader')),
    (r'^accounts/', include('feedhq.profiles.urls')),
    (r'^', include('feedhq.feeds.urls', namespace='feeds')),
)

urlpatterns += patterns(
    'ratelimitbackend.views',
    url(r'^login/$', 'login', {'authentication_form': AuthForm}, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedhq/feeds/views.py
import json
import logging
import opml
import re

from collections import defaultdict

from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse, reverse_lazy
from django.db import transaction
from django.db.models import Sum
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader, RequestContext
from django.template.defaultfilters import slugify
from django.utils.html import format_html
from django.utils.translation import ugettext as _, ungettext
from django.views import generic
from elasticsearch.exceptions import RequestError, ConflictError

from .. import es
from ..decorators import login_required
from ..tasks import enqueue
from .models import Category, Entry, UniqueFeed
from .forms import (CategoryForm, FeedForm, OPMLImportForm, ActionForm,
                    ReadForm, SubscriptionFormSet, UndoReadForm, user_lock)
from .tasks import read_later

"""
Each view displays a list of entries, with a level of filtering:
    - home: all entries
    - category: entries in a specific category
    - feed: entries for a specific feed
    - item: a single entry

Entries are paginated.
"""

logger = logging.getLogger(__name__)

MEDIA_RE = re.compile(
    r'.*<(img|audio|video|iframe|object|embed|script|source)\s+.*',
    re.UNICODE | re.DOTALL)


class Keyboard(generic.TemplateView):
    template_name = 'feeds/keyboard.html'
keyboard = Keyboard.as_view()


def paginate(object_list, page=1, nb_items=25, force_count=None):
    """
    Simple generic paginator for all the ``Entry`` lists
    """
    if force_count is not None:
        object_list.count = lambda x: force_count

    paginator = Paginator(object_list, nb_items)

    try:
        paginated = paginator.page(page)
    except (EmptyPage, InvalidPage):
        paginated = paginator.page(paginator.num_pages)

    return paginated, paginator._count


@login_required
def entries_list(request, page=1, only_unread=False, category=None, feed=None,
                 starred=False):
    """
    Displays a paginated list of entries.

    ``page``: the page number
    ``only_unread``: filters the list to display only the new entries
    ``category``: (slug) if set, will filter the entries of this category
    ``feed``: (object_id) if set, will filter the entries of this feed

    Note: only set category OR feed. Not both at the same time.
    """
    page = int(page)
    user = request.user
    es_entries = es.manager.user(request.user).defer(
        'content', 'guid', 'tags', 'read_later_url',
        'author', 'broadcast', 'link', 'starred',
    ).query_aggregate('all_unread', read=False)
    if only_unread:
        es_entries = es_entries.filter(read=False)

    if category is not None:
        category = get_object_or_404(user.categories, slug=category)
        all_url = reverse('feeds:category', args=[category.slug])
        unread_url = reverse('feeds:unread_category', args=[category.slug])
        es_entries = es_entries.filter(category=category.pk).query_aggregate(
            'all', category=category.pk).query_aggregate(
                'unread', category=category.pk, read=False)
        entries = user.entries.filter(feed__category=category)

    if feed is not None:
        feed = get_object_or_404(user.feeds.select_related('category'),
                                 pk=feed)
        all_url = reverse('feeds:feed', args=[feed.pk])
        unread_url = reverse('feeds:unread_feed', args=[feed.pk])

        category = feed.category
        es_entries = es_entries.filter(feed=feed.pk).query_aggregate(
            'all', feed=feed.pk).query_aggregate(
                'unread', feed=feed.pk, read=False)
        entries = feed.entries.all()

    if starred is True:
        es_entries = es_entries.filter(starred=True).query_aggregate(
            'all', starred=True).query_aggregate(
                'unread', starred=True, read=False)
        entries = user.entries.filter(starred=True)
        all_url = reverse('feeds:stars')
        unread_url = None

    if feed is None and category is None and starred is not True:
        entries = user.entries.all()
        all_url = reverse('feeds:home')
        unread_url = reverse('feeds:unread')
        es_entries = es_entries.query_aggregate('all').query_aggregate(
            'unread', read=False)

    entries = entries.select_related('feed', 'feed__category')
    if user.oldest_first:
        entries = entries.order_by('date', 'id')
        es_entries = es_entries.order_by('timestamp', 'id')

    if request.method == 'POST':
        if request.POST['action'] in (ReadForm.READ_ALL, ReadForm.READ_PAGE):
            pages_only = request.POST['action'] == ReadForm.READ_PAGE
            form = ReadForm(entries, es_entries, feed, category, user,
                            pages_only=pages_only, data=request.POST)
            if form.is_valid():
                pks = form.save()
                undo_form = loader.render_to_string('feeds/undo_read.html', {
                    'form': UndoReadForm(initial={
                        'pks': json.dumps(pks, separators=(',', ':'))}),
                    'action': request.get_full_path(),
                }, context_instance=RequestContext(request))
                message = ungettext(
                    '1 entry has been marked as read.',
                    '%(value)s entries have been marked as read.',
                    'value') % {'value': len(pks)}
                messages.success(request,
                                 format_html(u"{0} {1}", message, undo_form))

        elif request.POST['action'] == 'undo-read':
            form = UndoReadForm(user, data=request.POST)
            if form.is_valid():
                count = form.save()
                messages.success(
                    request, ungettext(
                        '1 entry has been marked as unread.',
                        '%(value)s entries have been marked as unread.',
                        'value') % {'value': count})

        if only_unread:
            return redirect(unread_url)
        else:
            return redirect(all_url)

    if user.es:
        try:
            entries = es_entries.fetch(page=page,
                                       per_page=user.entries_per_page,
                                       annotate=user)
        except RequestError as e:
            if 'No mapping found' not in e.error:  # index is empty
                raise
            entries = []
            user._unread_count = unread_count = total_count = 0
        else:
            aggs = entries['aggregations']
            entries = entries['hits']
            unread_count = aggs['entries']['unread']['doc_count']
            total_count = aggs['entries']['all']['doc_count']
            user._unread_count = aggs['entries']['all_unread']['doc_count']
        card = unread_count if only_unread else total_count
        num_pages = card // user.entries_per_page
        if card % user.entries_per_page:
            num_pages += 1
        entries = {
            'object_list': entries,
            'paginator': {
                'num_pages': num_pages,
            },
            'has_previous': page > 1,
            'has_next': page < num_pages,
            'previous_page_number': page - 1,
            'next_page_number': page + 1,
            'number': page,
        }

    else:
        unread_count = entries.filter(read=False).count()
        if only_unread:
            total_count = entries.count()
            entries = entries.filter(read=False)
            entries, foo = paginate(entries, page=page,
                                    force_count=unread_count,
                                    nb_items=request.user.entries_per_page)
        else:
            entries, total_count = paginate(
                entries, page=page, nb_items=request.user.entries_per_page)

    request.session['back_url'] = request.get_full_path()

    # base_url is a variable that helps the paginator a lot. The drawback is
    # that the paginator can't use reversed URLs.
    base_url = unread_url if only_unread else all_url

    context = {
        'category': category,
        'feed': feed,
        'entries': entries,
        'only_unread': only_unread,
        'unread_count': unread_count,
        'total_count': total_count,
        'all_url': all_url,
        'unread_url': unread_url,
        'base_url': base_url,
        'stars': starred,
        'all_unread': (aggs['entries']['unread']['doc_count'] if user.es
                       else user.entries.unread()),
        'entries_template': 'feeds/entries_include.html',
    }
    if unread_count:
        context['read_all_form'] = ReadForm()
        context['read_page_form'] = ReadForm(pages_only=True, initial={
            'action': ReadForm.READ_PAGE,
            'pages': json.dumps([int(page)]),
        })
        context['action'] = request.get_full_path()
    if user.es:
        if (
            len(entries['object_list']) == 0 and
            request.user.feeds.count() == 0
        ):
            context['noob'] = True
    else:
        if entries.paginator.count == 0 and request.user.feeds.count() == 0:
            context['noob'] = True

    if request.is_ajax():
        template_name = context['entries_template']
    else:
        template_name = 'feeds/entries_list.html'

    return render(request, template_name, context)


class SuccessMixin(object):
    success_message = None

    def get_success_message(self):
        return self.success_message

    def form_valid(self, form):
        response = super(SuccessMixin, self).form_valid(form)
        msg = self.get_success_message()
        if msg is not None:
            messages.success(self.request, msg)
        return response


class CategoryMixin(SuccessMixin):
    form_class = CategoryForm
    success_url = reverse_lazy('feeds:manage')

feedhq/views.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth.views import logout as do_logout
from django.http import (HttpResponse, HttpResponsePermanentRedirect,
                         HttpResponseNotAllowed)


robots = lambda _: HttpResponse('User-agent: *\nDisallow:\n',
                                mimetype='text/plain')

humans = lambda _: HttpResponse(u"""/* TEAM */
    Main developer: Bruno Renié
    Contact: contact [at] feedhq.org
    Twitter: @brutasse, @FeedHQ
    From: Switzerland

/* SITE */
    Language: English
    Backend: Django, PostgreSQL, Redis
    Frontend: SCSS, Compass, Iconic
""", mimetype='text/plain; charset=UTF-8')

favicon = lambda _: HttpResponsePermanentRedirect(
    '%score/img/icon-rss.png' % settings.STATIC_URL
)

touch_icon = lambda _: HttpResponsePermanentRedirect(
    '%sfeeds/img/touch-icon-114.png' % settings.STATIC_URL
)


def logout(request):
    if request.method != 'POST':
        return HttpResponseNotAllowed(["POST"], "Logout via POST only")
    return do_logout(request)

feedhq/templates/anonymous_navigation.html
<li><a href="{% url "login" %}">{% trans "Sign in" %}</a></li>

feedhq/templates/base.html
{% load staticfiles sekizai_tags %}<!DOCTYPE html>
<html xml:lang="en" lang="en">
	<head>
		<title>{% block title %}{% trans "Home" %}{% endblock %} &mdash; FeedHQ</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<link rel="shortcut icon" href="{% static "core/img/icon-rss.png" %}">
		<link rel="stylesheet" type="text/css" href="{% static "core/css/screen.css" %}">
		{% if user.is_authenticated %}
		<link rel="stylesheet" type="text/css" href="{% static "core/css/fonts/"|add:user.font|add:".css" %}">
		{% else %}
		<link rel="stylesheet" type="text/css" href="{% static "core/css/fonts/pt-serif.css" %}">
		{% endif %}
		<link rel="apple-touch-icon-precomposed" href="{% static "core/img/touch-icon-57.png" %}">
		<link rel="apple-touch-icon-precomposed" href="{% static "core/img/touch-icon-72.png" %}" sizes="72x72">
		<link rel="apple-touch-icon-precomposed" href="{% static "core/img/touch-icon-114.png" %}" sizes="114x114">
		<link rel="apple-touch-icon-precomposed" href="{% static "core/img/touch-icon-144.png" %}" sizes="144x144">
		{% render_block "css" %}
	</head>
	<body id="{% block bodyid %}default{% endblock %}" data-view="{% block view %}list{% endblock %}">
		<div id="root">
			<div>
			<div id="header"{% block header_mode %}{% endblock %}>
				<div class="container">
				<div class="row">
					<h1>{% if user.is_authenticated and only_unread %}{% url "feeds:unread" as home_url %}
						{% else %}{% url "feeds:home" as home_url %}{% endif %}
						<a class="home" href="{{ home_url }}" data-all="{% url "feeds:home" %}" data-unread="{% url "feeds:unread" %}" data-mousetrap="g h">FeedHQ</a>
						{% if user.is_authenticated %}
							<a class="unread" title="{% trans "Unread entries" %}" href="{% url "feeds:unread" %}">{{ user.unread_count }}</a>
						{% endif %}
					</h1>
					{% block extra_header %}{% endblock %}
					<div id="navigation">
						<ul>{% spaceless %}
							{% include "navigation.html" %}
						</ul>{% endspaceless %}
					</div>
				</div>
				</div>
			</div>
			<div id="content">
				{% if messages %}
					<div id="messages">
						{% for m in messages %}
							<div class="{{ m.tags }}">{{ m|safe }}</div>
						{% endfor %}
					</div>
				{% endif %}
				{% block actions %}{% endblock %}
				{% block content %}{% endblock %}
			</div>

			<div id="keyboard" class="modal hide fade" data-url="{% url "feeds:keyboard" %}"></div>
			</div>
			<div id="root_footer"></div>
		</div>
		<div id="footer">
			<div class="container">
				<div>{% include "footer.html" %}</div>
			</div>
		</div>
<script type="text/javascript" src="{% static "core/js/bundle.min.js" %}"></script>
{% render_block "js" %}

	</body>
</html>

feedhq/templates/field.html
{% load floppyforms %}
{% if not field.is_hidden %}
	<div class="field{% if forloop.first %} first{% endif %}{% if forloop.last %} last{% endif %}">
		<div class="row">
		<div class="title">
			<h6>{{ field.label_tag }}</h6>
		</div>
		<div class="input">
			<p>{% widget field %}</p>
			{{ field.errors }}
			{% if field.help_text %}<p class="helptext">{{ field.help_text|safe }}</p>{% endif %}
		</div>
		</div>
	</div>
{% else %}
	{{ field }}
{% endif %}

feedhq/templates/footer.html
<a href="https://github.com/feedhq/feedhq">FeedHQ</a> - {% blocktrans %}a <a href="https://www.djangoproject.com">Django</a> joint{% endblocktrans %} - &copy; 2009-{% now "Y" %} Bruno Renié.

feedhq/templates/form.html
{% csrf_token %}
{% if form.errors and not form.non_field_errors %}
	<p class="errorlist">{% trans "Please correct the errors below and submit the form again." %}</p>
{% endif %}
{{ form.non_field_errors }}
{% for field in form %}
	{% include "field.html" %}
{% endfor %}

feedhq/templates/navigation.html
{% if not user.is_authenticated %}
	{% include "anonymous_navigation.html" %}
{% else %}
	<li>
		<strong><a class="profile" href="{% url "profile" %}">{{ user.username }}</a></strong>
		<ul>
			<li><a href="{% url "feeds:dashboard" %}" data-mousetrap="g d" class="add" title="{% trans "Dashboard" %}"><span class="icon-dashboard"></span>{% trans "Dashboard" %}</a></li>
			<li><a href="{% url "feeds:stars" %}" data-mousetrap="g s" class="add" title="{% trans "Starred" %}"><span class="icon-star"></span>{% trans "Starred" %}</a></li>
			<li><a href="{% url "feeds:manage" %}" data-mousetrap="g m" class="add" title="{% trans "Manage feeds" %}"><span class="icon-cog"></span>{% trans "Manage feeds" %}</a></li>
			<li><a href="{% url "feeds:add_category" %}" class="add" title="{% trans "Add a category" %}"><span class="icon-tag"></span>{% trans "Add category" %}</a></li>
			<li><a href="{% url "feeds:add_feed" %}" data-mousetrap="a" class="add" title="{% trans "Add a feed" %}"><span class="icon-rss"></span>{% trans "Add feed" %}</a></li>
			<li class="sep"><a href="{% url "feeds:import_feeds" %}" class="add" title="{% trans "Import feeds" %}"><span class="icon-cloud-upload"></span>{% trans "Import" %}</a></li>
			<li><a href="{% url "profile" %}">{% trans "Account settings" %}</a></li>
			<li><form method="post" action="{% url "logout" %}" id="logout">
				{% csrf_token %}
				<input type="submit" value="{% trans "Logout" %}"></form>
			</li>
		</ul>
	</li>
{% endif %}