feedhq/feeds/urls.py
from django.conf.urls import url, patterns

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.entries_list, name='home'),
    url(r'^(?P<page>\d+)/$', views.entries_list, name='home'),
    url(r'^unread/$', views.entries_list,
        {'only_unread': True}, name='unread'),
    url(r'^unread/(?P<page>\d+)/$', views.entries_list,
        {'only_unread': True}, name='unread'),

    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/unread/$', views.dashboard,
        {'only_unread': True}, name='unread_dashboard'),

    url(r'^stars/$', views.entries_list,
        {'starred': True}, name='stars'),

    url(r'^stars/(?P<page>\d+)/$', views.entries_list,
        {'starred': True}, name='stars'),

    url(r'^manage/$', views.manage, name='manage'),

    url(r'^import/$', views.import_feeds, name='import_feeds'),
    url(r'^subscribe/$', views.subscribe, name='subscribe'),
    url(r'^keyboard/$', views.keyboard, name='keyboard'),

    # Categories
    url(r'^category/add/$', views.add_category, name='add_category'),
    url(r'^category/(?P<slug>[\w_-]+)/edit/$', views.edit_category,
        name='edit_category'),
    url(r'^category/(?P<slug>[\w_-]+)/delete/$', views.delete_category,
        name='delete_category'),

    url(r'^category/(?P<category>[\w_-]+)/$', views.entries_list,
        name='category'),

    url(r'^category/(?P<category>[\w_-]+)/(?P<page>\d+)/$',
        views.entries_list, name='category'),

    url(r'^category/(?P<category>[\w_-]+)/unread/$', views.entries_list,
        {'only_unread': True}, name='unread_category'),
    url(r'^category/(?P<category>[\w_-]+)/unread/(?P<page>\d+)/$',
        views.entries_list, {'only_unread': True}, name='unread_category'),

    # Feeds
    url(r'^feed/add/$', views.add_feed, name='add_feed'),
    url(r'^feed/(?P<feed>\d+)/edit/$', views.edit_feed, name='edit_feed'),
    url(r'^feed/(?P<feed>\d+)/delete/$', views.delete_feed,
        name='delete_feed'),

    url(r'^feed/(?P<feed>\d+)/$', views.entries_list, name='feed'),
    url(r'^feed/(?P<feed>\d+)/(?P<page>\d+)/$', views.entries_list,
        name='feed'),
    url(r'^feed/(?P<feed>\d+)/unread/$', views.entries_list,
        {'only_unread': True}, name='unread_feed'),
    url(r'^feed/(?P<feed>\d+)/unread/(?P<page>\d+)/$', views.entries_list,
        {'only_unread': True}, name='unread_feed'),

    # Entries
    url(r'^entries/(?P<entry_id>\d+)/$', views.item, name='item'),
)

feedhq/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, patterns, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from ratelimitbackend import admin
admin.autodiscover()

from . import views
from .profiles.forms import AuthForm


urlpatterns = patterns(
    '',
    (r'^admin/rq/', include('django_rq_dashboard.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^subscriber/', include('django_push.subscriber.urls')),
    url(r'^robots.txt$', views.robots),
    url(r'^humans.txt$', views.humans),
    url(r'^favicon.ico$', views.favicon),
    url(r'^apple-touch-icon-precomposed.png$', views.touch_icon),
    url(r'^apple-touch-icon.png$', views.touch_icon),
    (r'^', include('feedhq.reader.urls', namespace='reader')),
    (r'^accounts/', include('feedhq.profiles.urls')),
    (r'^', include('feedhq.feeds.urls', namespace='feeds')),
)

urlpatterns += patterns(
    'ratelimitbackend.views',
    url(r'^login/$', 'login', {'authentication_form': AuthForm}, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedhq/profiles/models.py
import json
import pytz

from datetime import timedelta

from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, UserManager,
                                        PermissionsMixin)
from django.db import models
from django.db.models import Max
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from .. import es
from ..utils import get_redis_connection

TIMEZONES = [
    (tz, _(tz)) for tz in pytz.common_timezones
]

ENTRIES_PER_PAGE = (
    (25, 25),
    (50, 50),
    (100, 100),
)


class User(PermissionsMixin, AbstractBaseUser):
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    NONE = ''
    READABILITY = 'readability'
    READITLATER = 'readitlater'
    INSTAPAPER = 'instapaper'
    WALLABAG = 'wallabag'
    POCKET = 'pocket'
    READ_LATER_SERVICES = (
        (NONE, _('None')),
        (READABILITY, u'Readability'),
        (READITLATER, u'Read it later'),
        (INSTAPAPER, u'Instapaper'),
        (WALLABAG, u'Wallabag'),
        (POCKET, u'Pocket'),
    )

    FONT_DROID_SANS = 'droid-sans'
    FONT_DROID_SERIF = 'droid-serif'
    FONT_GENTIUM_BASIC = 'gentium-basic'
    FONT_MERRIWEATHER = 'merriweather'
    FONT_PALATINO = 'palatino'
    FONT_POLY = 'poly'
    FONT_PT_SERIF = 'pt-serif'
    FONT_ABEL = 'abel'
    FONT_HELVETICA = 'helvetica'
    FONT_MULI = 'muli'
    FONT_OPEN_SANS = 'open-sans'
    FONT_PT_SANS = 'pt-sans'
    FONT_UBUNTU_CONDENSED = 'ubuntu-condensed'
    FONT_SOURCE_SANS_PRO = 'source-sans-pro'

    FONTS = (
        (
            _('Serif'), (
                (FONT_DROID_SERIF, 'Droid Serif'),
                (FONT_GENTIUM_BASIC, 'Gentium Basic'),
                (FONT_MERRIWEATHER, 'Merriweather'),
                (FONT_PALATINO, _('Palatino (system font)')),
                (FONT_POLY, 'Poly'),
                (FONT_PT_SERIF, 'PT Serif'),
            )
        ), (
            _('Sans Serif'), (
                (FONT_ABEL, 'Abel'),
                (FONT_DROID_SANS, 'Droid Sans'),
                (FONT_HELVETICA, _('Helvetica (system font)')),
                (FONT_MULI, 'Muli'),
                (FONT_OPEN_SANS, 'Open Sans'),
                (FONT_PT_SANS, 'PT Sans'),
                (FONT_UBUNTU_CONDENSED, 'Ubuntu Condensed'),
                (FONT_SOURCE_SANS_PRO, 'Source Sans Pro'),
            )
        )
    )

    username = models.CharField(max_length=75, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=75)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_suspended = models.BooleanField(default=False, db_index=True)
    date_joined = models.DateTimeField(default=timezone.now)
    timezone = models.CharField(_('Time zone'), max_length=75,
                                choices=TIMEZONES, default='UTC')
    entries_per_page = models.IntegerField(_('Entries per page'), default=50,
                                           choices=ENTRIES_PER_PAGE)
    endless_pages = models.BooleanField(
        _('Endless pages'), default=True,
        help_text=_("Check this box if you'd like to use a 'load more' "
                    "button instead of the page links."))

    oldest_first = models.BooleanField(
        _('Oldest entries first'), default=False,
        help_text=_("Check this box if you'd like to have the oldest "
                    "entries appear first."))
    read_later = models.CharField(_('Read later service'), blank=True,
                                  choices=READ_LATER_SERVICES, max_length=50)
    read_later_credentials = models.TextField(_('Read later credentials'),
                                              blank=True)

    sharing_twitter = models.BooleanField(_('Enable tweet button'),
                                          default=False)
    sharing_gplus = models.BooleanField(_('Enable +1 button (Google+)'),
                                        default=False)
    sharing_email = models.BooleanField(_('Enable Mail button'), default=False)

    allow_media = models.BooleanField(_('Automatically allow external media'),
                                      default=False)

    font = models.CharField(
        _('Text font'), max_length=75, choices=FONTS, default=FONT_PT_SERIF,
        help_text=_('Non-system fonts are served by Google Web Fonts.'),
    )

    ttl = models.PositiveIntegerField(
        _('Retention days'), default=30,
        help_text=_('Number of days after which entries are deleted. The more '
                    'history you keep, the less snappy FeedHQ becomes. '
                    'Starred items are not deleted.'))
    es = models.NullBooleanField(default=True)

    objects = UserManager()

    class Meta:
        db_table = 'auth_user'

    def get_short_name(self):
        return self.username

    @property
    def last_update_key(self):
        return 'user:{0}:updates'.format(self.pk)

    @property
    def wallabag_url(self):
        return json.loads(self.read_later_credentials)['wallabag_url']

    @property
    def unread_count(self):
        if hasattr(self, '_unread_count'):
            return self._unread_count
        if self.es:
            return es.client.count(es.user_alias(self.pk),
                                   doc_type='entries',
                                   body={'query': {
                                       'term': {
                                           'read': False,
                                       }}})['count']
        else:
            return self.entries.unread()

    def last_updates(self):
        redis = get_redis_connection()
        values = redis.zrange(self.last_update_key, 0, 10**11, withscores=True)
        updates = {}
        for url, timestamp in values:
            updates[url.decode('utf-8')] = int(timestamp)
        return updates

    def refresh_updates(self):
        redis = get_redis_connection()
        last_updates = self.last_updates()
        urls = self.feeds.values_list('pk', 'url')
        for pk, url in urls:
            if url in last_updates:
                continue
            value = self.entries.filter(feed_id=pk).aggregate(
                date=Max('date'))['date']
            value = float(value.strftime('%s')) if value else 0
            redis.zadd(self.last_update_key, url, value)
        return self.last_updates()

    def ensure_alias(self):
        name = es.user_alias(self.pk)
        es.client.indices.put_alias(
            index=settings.ES_INDEX,
            name=name,
            body={
                'routing': self.pk,
                'filter': {'term': {'user': self.pk}},
            },
        )
        return name

    def save(self, *args, **kwargs):
        ret = super(User, self).save(*args, **kwargs)
        if self.es:
            self.ensure_alias()
        return ret

    def index_entries(self):
        if self.es:
            return
        name = self.ensure_alias()
        for feed in self.feeds.all():
            entries = feed.entries.all()
            docs = [doc.serialize() for doc in entries]
            if not docs:
                continue
            es.bulk(docs, index=name, timeout=60, raise_on_error=True)
        self.es = True
        self.save(update_fields=['es'])

    def delete_feed_entries(self, *pks):
        return es.client.delete_by_query(
            index=es.user_alias(self.pk),
            doc_type='entries',
            body={'query': {'filtered': {'filter': {'or': [
                {'term': {'feed': pk}} for pk in pks
            ]}}}},
        )

    def delete_category_entries(self, pk):
        return es.client.delete_by_query(
            index=es.user_alias(self.pk),
            doc_type='entries',
            body={'query': {'term': {'category': pk}}},
        )

    def delete_old(self):
        limit = timezone.now() - timedelta(days=self.ttl)
        if self.es:
            es.client.delete_by_query(
                index=es.user_alias(self.pk),
                doc_type='entries',
                body={'query': {'filtered': {
                    'filter': {'and': [
                        {'range': {'timestamp': {'lte': limit}}},
                        {'term': {'starred': False}},
                    ]},
                }}},
            )
        else:
            self.entries.filter(date__lte=limit).delete()

feedhq/feeds/templates/feeds/category_confirm_delete.html
{% extends "base.html" %}

{% block title %}{% trans "Confirm deletion" %}{% endblock %}

{% block content %}
	<h2>{% trans "Confirm deletion" %}</h2>
	<form method="post" action="{% url "feeds:delete_category" object.slug %}" id="delete">
		<p>{% blocktrans %}You are about to delete the category: <em>{{ object }}</em>. Are you sure?{% endblocktrans %}</p>
		<ul>
			<li>{% trans "There is no undo" %}</li>
			<li>{% blocktrans count counter=feed_count %}{{ feed_count }} feed will be deleted.{% plural %}{{ feed_count }} feeds will be deleted.{% endblocktrans %}</li>
			<li>{% blocktrans count counter=entry_count %}{{ entry_count }} entry will be deleted.{% plural %}{{ entry_count }} entries will be deleted.{% endblocktrans %}</li>
		</ul>
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Delete" %}">
				<a href="{% url "feeds:category" object.slug %}">{% trans "Cancel" %}</a>
			</div>
		</div>
	</form>
{% endblock %}

feedhq/feeds/templates/feeds/dashboard.html
{% extends "base.html" %}

{% block title %}{% trans "Dashboard" %}{% endblock %}

{% block content %}
	<div class="figures full">
		<div class="count">
		<a href="{% if only_unread %}{% url 'feeds:unread_dashboard' %}{% else %}{% url 'feeds:dashboard' %}{% endif %}">{% trans "Dashboard" %}</a>

		<div class="navlist inline">{% spaceless %}
			<a href="{% url 'feeds:dashboard' %}"{% if not only_unread %} class="current"{% endif %}>{% trans "all" %}</a>
			<a href="{% url 'feeds:unread_dashboard' %}"{% if only_unread %} class="current"{% endif %}>{% trans "unread" %}</a>
		{% endspaceless %}</div>
		</div>
	</div>

	<div class="row">
	<div class="col first">
		{% for cat in categories %}
			<div class="category">
				{% if cat.slug %}
					<h3><a href="{% url "feeds:category" cat.slug %}">{{ cat.name }}</a> <a class="cat {{ cat.color }}" href="{% url "feeds:unread_category" cat.slug %}">{{ cat.unread_count|default:"0" }}</a></h3>
				{% else %}
					<br>
				{% endif %}
				<ul>{% for feed in cat.feeds.all %}
						{% if feed.unread_count > 0 or not only_unread %}
						<li{% if feed.favicon %} style="background-image: url('{{ feed.favicon.url }}');"{% endif %}{% if feed.unread_count %} class="new"{% endif %}><a href="{% url "feeds:feed" feed.pk %}">{{ feed }}</a>{% if feed.unread_count %} <a href="{% url "feeds:unread_feed" feed.pk %}" class="unread">{{ feed.unread_count }}{% endif %}</a></li>
						{% endif %}
				{% endfor %}</ul>
			</div>
			{% if forloop.counter in breaks %}</div><div class="col">{% endif %}
		{% endfor %}
	</div>
	</div>
{% endblock %}

feedhq/feeds/templates/feeds/edit_category.html
{% extends "base.html" %}

{% block title %}{% blocktrans with name=category.name %}Edit {{ name }}{% endblocktrans %}{% endblock %}

{% block content %}
	<h2>{{ category.name }}</h2>
	<form method="post" action="{% url "feeds:edit_category" category.slug %}" id="category">
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Save changes" %}">
				<a class="delete" href="{% url "feeds:delete_category" category.slug %}">{% trans "Delete this category" %}</a>
			</div>
		</div>
	</form>
{% endblock %}

feedhq/feeds/templates/feeds/edit_feed.html
{% extends "base.html" %}

{% block title %}{% blocktrans with name=feed.name %}Edit {{ name }}{% endblocktrans %}{% endblock %}

{% block content %}
	<h2>{% blocktrans with name=feed.name %}Edit {{ name }}{% endblocktrans %}</h2>
	<form method="post" action="{% url "feeds:edit_feed" feed.pk %}" id="feed">
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Save changes" %}">
				<a class="delete" href="{% url "feeds:delete_feed" feed.pk %}">{% trans "Delete this feed" %}</a>
			</div>
		</div>
	</form>
{% endblock %}

feedhq/feeds/templates/feeds/entries_list.html
{% extends "base.html" %}

{% block title %}{% if unread_count %}({{ unread_count }}) {% endif %}
	{% if feed %}{{ feed.name }}{% else %}
		{% if category %}{{ category.name }}{% else %}
			{{ block.super }}
{% endif %}{% endif %}{% endblock %}

{% block content %}
	{% if noob %}
		<div class="help"><div class="content">
			<h2>{% trans "Getting started" %}</h2>
			<p>{% trans "Hi! Looks like you're new here. Here are a couple of things you can do to get started with FeedHQ:" %}</p>
			<ul>
				<li><a href="{% url "feeds:add_category" %}">{% trans "Create a category" %}</a>.</li>
				<li><a href="{% url "feeds:add_feed" %}">{% trans "Add a feed" %}</a>.</li>
				<li><a href="{% url "feeds:import_feeds" %}">{% trans "Got an OPML dump? Import it!" %}</a> {% blocktrans %}If you're a Google Reader user, you can get your OPML dump <a href="http://www.google.com/reader/subscriptions/export">here</a>. Just download it and import it on FeedHQ.{% endblocktrans %}</li>
			</ul>
			<p>{% trans "These three features can be accessed using the menu on the top right. This page will self-destruct as soon as you add your first feed. Enjoy!" %}</p>
		</div></div>
	{% else %}
		<div class="figures{% if not category %} full{% endif %}">
			<div class="count">{% spaceless %}
				{% if category %}
					<a class="{{ category.color }}" href="{% if only_unread %}{% url "feeds:unread_category" category.slug %}{% else %}{% url "feeds:category" category.slug %}{% endif %}">{{ category }}</a>
					{% if feed %} / {% endif %}
				{% endif %}
				{% if feed %}
					<a class="{{ feed.category.color|default:feed.color }}" href="{% if only_unread %}{% url "feeds:unread_feed" feed.pk %}{% else %}{% url "feeds:feed" feed.pk %}{% endif %}">{{ feed }}</a>
				{% endif %}{% endspaceless %}
				<div class="navlist inline">{% spaceless %}
					{% if stars %}<i class="icon-star"></i>&nbsp;{% endif %}
					<a href="{{ all_url }}"{% if not only_unread %} class="current"{% endif %}>{% trans "all" %} <span class="ct">{{ total_count }}</span></a>
					{% if unread_url %}<a href="{{ unread_url }}"{% if only_unread %} class="current"{% endif %}>{% trans "unread" %} <span class="ct">{{ unread_count }}</span></a>{% endif %}
					{% if feed %}
					<a href="{% url "feeds:edit_feed" feed.pk %}" class="tultip" title="{% trans "Edit feed" %}">
						<i class="icon-edit"></i>
						<span class="legend">{% trans "Edit feed" %}</span>
					</a>
					{% endif %}
					{% if read_page_form %}
						<form data-mousetrap="shift+a" method="post" action="{{ action }}" class="read" id="read-page">
							{% include "form.html" with form=read_page_form %}
							<button class="tultip" title="{% trans "Mark page as read" %}">
								<i class="icon-ok-circle"></i>
								<span class="legend">{% trans "Mark page as read" %}</span>
							</button>
						</form>
					{% endif %}
					{% if read_all_form %}
						<form data-mousetrap="mod+shift+a" method="post" action="{{ action }}" class="read" id="read-all">
							{% include "form.html" with form=read_all_form %}
							<button class="tultip" title="{% trans "Mark all as read" %}">
								<i class="icon-ok-sign"></i>
								<span class="legend">{% trans "Mark all as read" %}</span>
							</button>
						</form>
					{% endif %}
				{% endspaceless %}</div>
			</div>
			{% if not user.endless_pages %}
				<div class="pagination">{% include "feeds/paginator.html" %}</div>
			{% endif %}
		</div>

		<ul id="entries">
			{% include entries_template %}
		</ul>

		{% if user.endless_pages %}
			{% if entries.paginator.num_pages > 1 and entries.has_next %}
				<a href="{{ base_url }}{{ entries.next_page_number }}/" title="{% trans "Load more" %}" data-loading="{% trans "Loading…" %}" class="feedhq-more" data-mousetrap="l">
					{% trans "Load more" %}
				</a>
			{% endif %}
		{% else %}
			<div class="figures bottom">
				<div class="pagination">{% include "feeds/paginator.html" %}</div>
			</div>
		{% endif %}
	{% endif %}
{% endblock %}

feedhq/feeds/templates/feeds/entry_detail.html
{% extends "feeds/entries_list.html" %}
{% load staticfiles sekizai_tags %}

{% block title %}{{ object.sanitized_title|safe }}{% endblock %}

{% block view %}detail{% endblock %}

{% block content %}
	{% include "feeds/entry_navigation.html" %}
	<div id="entry" class="feedhq-media feedhq-highlight">
		<h2>{{ object.sanitized_title|safe }}
			<a href="{% if only_unread %}{% url "feeds:unread_feed" object.feed.pk %}{% else %}{% url "feeds:feed" object.feed.pk %}{% endif %}" class="cat {{ object.feed.category.color|default:object.feed.color }}">{{ object.feed.name }}</a>
			{% if object.feed.category %}<a href="{% if only_unread %}{% url "feeds:unread_category" object.feed.category.slug %}{% else %}{% url "feeds:category" object.feed.category.slug %}{% endif %}" class="cat opaque {{ object.feed.category.color }}">{{ object.feed.category.name }}</a>{% endif %}
		</h2>
		<div class="row">
			{% include "feeds/entry_links.html" %}
			<div class="actions navlist">
				{% if not object.read_later_url and user.read_later and user.read_later != "wallabag" %}
					<form method="post" action="{% url "feeds:item" object.pk %}" id="read-later" data-mousetrap="i">
						{% csrf_token %}
						<input type="hidden" name="action" value="read_later">
						<button class="tultip" type="submit" title="{% blocktrans with read_later=user.get_read_later_display %}Add to {{ read_later }}{% endblocktrans %}">
							<i class="icon-book"></i>
							<span class="legend">{% blocktrans with read_later=user.get_read_later_display %}Add to {{ read_later }}{% endblocktrans %}</span>
						</button>
					</form>
				{% endif %}
				{% if user.read_later == "wallabag" %}
					<a class="tultip" title="{% trans "Add to Wallabag" %}" href="{{ user.wallabag_url }}?action=add&url={{ object.base64_url }}&autoclose=true" target="_blank" data-mousetrap="i">
						<i class="icon-book"></i>
						<span class="legend">{% trans "Add to Wallabag" %}</span>
					</a>
				{% endif %}
				<form method="post" action="{% url "feeds:item" object.pk %}" id="unread" data-mousetrap="m">
					{% csrf_token %}
					<input type="hidden" name="action" value="unread">
					<button class="tultip" type="submit" title="{% trans "Unread" %}">
						<i class="icon-eye-open"></i>
						<span class="legend">{% trans "Unread" %}</span>
					</button>
				</form>
				<form method="post" action="{% url "feeds:item" object.pk %}" id="star" data-mousetrap="s">
					{% csrf_token %}
					{% if object.starred %}
						<input type="hidden" name="action" value="unstar">
						<button class="tultip" type="submit" title="{% trans "Unstar" %}">
							<i class="icon-star-empty"></i>
							<span class="legend">{% trans "Unstar" %}</span>
						</button>
					{% else %}
						<input type="hidden" name="action" value="star">
						<button class="tultip" type="submit" title="{% trans "Star" %}">
							<i class="icon-star"></i>
							<span class="legend">{% trans "Star" %}</span>
						</button>
					{% endif %}
				</form>
				{% if user.sharing_email %}
					<a class="tultip" data-mousetrap="e" title="{% trans "Email" %}" href="mailto:?subject={{ object.title }}&body={{ object.link }}"><i class="icon-envelope-alt"></i><span class="legend">{% trans "Email" %}</span></a>
				{% endif %}
				{% if user.sharing_twitter %}
					<a target="_blank" class="tultip" data-mousetrap="t" title="{% trans "Tweet" %}" href="https://twitter.com/home?status={{ object.tweet|urlencode }}"><i class="icon-twitter"></i><span class="legend">{% trans "Tweet" %}</span></a>
				{% endif %}
				{% if user.sharing_gplus %}
					<a target="_blank" class="tultip" data-mousetrap="+" title="{% trans "Share on Google+" %}" href="https://plus.google.com/share?url={{ object.link }}"><i class="icon-google-plus"></i><span class="legend">{% trans "Share on Google+" %}</span></a>
				{% endif %}
			</div>
		</div>
		{% if has_media and not user.allow_media %}
			<div class="externalmedia">
				<form method="post" action="{% url "feeds:item" object.pk %}" class="images" id="images">
					{% csrf_token %}
					<input type="hidden" name="action" value="images">
					{% if object.feed.media_safe %}
						{% trans "External media is always displayed for this feed." %}
						<input type="submit" value="{% trans "Disable external media" %}" name="never">
					{% else %}
						{% if media_safe %}
							{% trans "External media is only displayed this time." %}
							<input type="submit" value="{% trans "Always display external media for this feed" %}" name="always">
						{% else %}
							{% trans "External media is hidden by default to protect your privacy. Show media:" %}
							<input type="submit" value="{% trans "once" %}" name="once">
							<input type="submit" value="{% trans "always" %}" name="always">
						{% endif %}
					{% endif %}
				</form>
			</div>
		{% endif %}
		<div class="content">
			{% if media_safe or object.feed.media_safe or user.allow_media %}
				{{ object.sanitized_content|safe }}
			{% else %}
				{{ object.sanitized_nomedia_content|safe }}
			{% endif %}
		</div>
		<div class="row">
			{% include "feeds/entry_links.html" %}
		</div>
	</div>
	{% include "feeds/entry_navigation.html" with place="bottom" %}
{% endblock %}

feedhq/feeds/templates/feeds/feed_confirm_delete.html
{% extends "base.html" %}

{% block title %}{% trans "Confirm deletion" %}{% endblock %}

{% block content %}
	<h2>{% trans "Confirm deletion" %}</h2>
	<form method="post" action="{% url "feeds:delete_feed" object.pk %}" id="delete">
		<p>{% blocktrans %}You are about to delete the feed: <em>{{ object }}</em>. Are you sure?{% endblocktrans %}</p>
		<ul>
			<li>{% trans "There is no undo." %}</li>
			<li>{% blocktrans count counter=entry_count %}{{ entry_count }} entry will be deleted.{% plural %}{{ entry_count }} entries will be deleted.{% endblocktrans %}</li>
		</ul>
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Delete" %}">
				<a href="{% url "feeds:feed" object.pk %}">{% trans "Cancel"%}</a>
			</div>
		</div>
	</form>
{% endblock %}

feedhq/feeds/templates/feeds/feed_form.html
{% extends "base.html" %}

{% block title %}{% trans "Add a feed" %}{% endblock %}

{% block content %}
	<h2>{% trans "Add a feed" %}</h2>
	<form method="post" action="{% url "feeds:add_feed" %}" id="feed">
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Add feed" %}">
				<a href="{% url "feeds:home" %}">{% trans "Cancel" %}</a>
			</div>
		</div>
	</form>
{% endblock %}