feedhq/feeds/urls.py
from django.conf.urls import url, patterns

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.entries_list, name='home'),
    url(r'^(?P<page>\d+)/$', views.entries_list, name='home'),
    url(r'^unread/$', views.entries_list,
        {'only_unread': True}, name='unread'),
    url(r'^unread/(?P<page>\d+)/$', views.entries_list,
        {'only_unread': True}, name='unread'),

    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/unread/$', views.dashboard,
        {'only_unread': True}, name='unread_dashboard'),

    url(r'^stars/$', views.entries_list,
        {'starred': True}, name='stars'),

    url(r'^stars/(?P<page>\d+)/$', views.entries_list,
        {'starred': True}, name='stars'),

    url(r'^manage/$', views.manage, name='manage'),

    url(r'^import/$', views.import_feeds, name='import_feeds'),
    url(r'^subscribe/$', views.subscribe, name='subscribe'),
    url(r'^keyboard/$', views.keyboard, name='keyboard'),

    # Categories
    url(r'^category/add/$', views.add_category, name='add_category'),
    url(r'^category/(?P<slug>[\w_-]+)/edit/$', views.edit_category,
        name='edit_category'),
    url(r'^category/(?P<slug>[\w_-]+)/delete/$', views.delete_category,
        name='delete_category'),

    url(r'^category/(?P<category>[\w_-]+)/$', views.entries_list,
        name='category'),

    url(r'^category/(?P<category>[\w_-]+)/(?P<page>\d+)/$',
        views.entries_list, name='category'),

    url(r'^category/(?P<category>[\w_-]+)/unread/$', views.entries_list,
        {'only_unread': True}, name='unread_category'),
    url(r'^category/(?P<category>[\w_-]+)/unread/(?P<page>\d+)/$',
        views.entries_list, {'only_unread': True}, name='unread_category'),

    # Feeds
    url(r'^feed/add/$', views.add_feed, name='add_feed'),
    url(r'^feed/(?P<feed>\d+)/edit/$', views.edit_feed, name='edit_feed'),
    url(r'^feed/(?P<feed>\d+)/delete/$', views.delete_feed,
        name='delete_feed'),

    url(r'^feed/(?P<feed>\d+)/$', views.entries_list, name='feed'),
    url(r'^feed/(?P<feed>\d+)/(?P<page>\d+)/$', views.entries_list,
        name='feed'),
    url(r'^feed/(?P<feed>\d+)/unread/$', views.entries_list,
        {'only_unread': True}, name='unread_feed'),
    url(r'^feed/(?P<feed>\d+)/unread/(?P<page>\d+)/$', views.entries_list,
        {'only_unread': True}, name='unread_feed'),

    # Entries
    url(r'^entries/(?P<entry_id>\d+)/$', views.item, name='item'),
)

feedhq/profiles/urls.py
from django.conf.urls import url, patterns, include

from . import views

urlpatterns = patterns(
    '',
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^sharing/$', views.sharing, name='sharing'),
    url(r'^bookmarklet/$', views.bookmarklet, name='bookmarklet'),
    url(r'^password/$', views.password, name='password'),
    url(r'^export/$', views.export, name='export'),
    url(r'^readlater/(?P<service>readability|readitlater|instapaper|'
        r'pocket|wallabag|none)/$',
        views.services, name='services'),
    url(r'^readlater/pocket/return/$', views.pocket, name='pocket_return'),
    url(r'^readlater/$', views.read_later, name='read_later'),
    url(r'^destroy/$', views.destroy, name='destroy_account'),
    url(r'^destroy/sent/$', views.destroy_sent, name='destroy_sent'),
    url(r'^destroy/confirm/(?P<token>[^\/]+)/$',
        views.destroy_confirm, name='destroy_confirm'),
    url(r'^destroy/done/$', views.destroy_done, name='destroy_done'),
    url(r'^recover/$', views.recover, name='password_reset_recover'),
    url(r'^', include('password_reset.urls')),
)

feedhq/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, patterns, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from ratelimitbackend import admin
admin.autodiscover()

from . import views
from .profiles.forms import AuthForm


urlpatterns = patterns(
    '',
    (r'^admin/rq/', include('django_rq_dashboard.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^subscriber/', include('django_push.subscriber.urls')),
    url(r'^robots.txt$', views.robots),
    url(r'^humans.txt$', views.humans),
    url(r'^favicon.ico$', views.favicon),
    url(r'^apple-touch-icon-precomposed.png$', views.touch_icon),
    url(r'^apple-touch-icon.png$', views.touch_icon),
    (r'^', include('feedhq.reader.urls', namespace='reader')),
    (r'^accounts/', include('feedhq.profiles.urls')),
    (r'^', include('feedhq.feeds.urls', namespace='feeds')),
)

urlpatterns += patterns(
    'ratelimitbackend.views',
    url(r'^login/$', 'login', {'authentication_form': AuthForm}, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedhq/profiles/models.py
import json
import pytz

from datetime import timedelta

from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, UserManager,
                                        PermissionsMixin)
from django.db import models
from django.db.models import Max
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from .. import es
from ..utils import get_redis_connection

TIMEZONES = [
    (tz, _(tz)) for tz in pytz.common_timezones
]

ENTRIES_PER_PAGE = (
    (25, 25),
    (50, 50),
    (100, 100),
)


class User(PermissionsMixin, AbstractBaseUser):
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    NONE = ''
    READABILITY = 'readability'
    READITLATER = 'readitlater'
    INSTAPAPER = 'instapaper'
    WALLABAG = 'wallabag'
    POCKET = 'pocket'
    READ_LATER_SERVICES = (
        (NONE, _('None')),
        (READABILITY, u'Readability'),
        (READITLATER, u'Read it later'),
        (INSTAPAPER, u'Instapaper'),
        (WALLABAG, u'Wallabag'),
        (POCKET, u'Pocket'),
    )

    FONT_DROID_SANS = 'droid-sans'
    FONT_DROID_SERIF = 'droid-serif'
    FONT_GENTIUM_BASIC = 'gentium-basic'
    FONT_MERRIWEATHER = 'merriweather'
    FONT_PALATINO = 'palatino'
    FONT_POLY = 'poly'
    FONT_PT_SERIF = 'pt-serif'
    FONT_ABEL = 'abel'
    FONT_HELVETICA = 'helvetica'
    FONT_MULI = 'muli'
    FONT_OPEN_SANS = 'open-sans'
    FONT_PT_SANS = 'pt-sans'
    FONT_UBUNTU_CONDENSED = 'ubuntu-condensed'
    FONT_SOURCE_SANS_PRO = 'source-sans-pro'

    FONTS = (
        (
            _('Serif'), (
                (FONT_DROID_SERIF, 'Droid Serif'),
                (FONT_GENTIUM_BASIC, 'Gentium Basic'),
                (FONT_MERRIWEATHER, 'Merriweather'),
                (FONT_PALATINO, _('Palatino (system font)')),
                (FONT_POLY, 'Poly'),
                (FONT_PT_SERIF, 'PT Serif'),
            )
        ), (
            _('Sans Serif'), (
                (FONT_ABEL, 'Abel'),
                (FONT_DROID_SANS, 'Droid Sans'),
                (FONT_HELVETICA, _('Helvetica (system font)')),
                (FONT_MULI, 'Muli'),
                (FONT_OPEN_SANS, 'Open Sans'),
                (FONT_PT_SANS, 'PT Sans'),
                (FONT_UBUNTU_CONDENSED, 'Ubuntu Condensed'),
                (FONT_SOURCE_SANS_PRO, 'Source Sans Pro'),
            )
        )
    )

    username = models.CharField(max_length=75, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=75)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_suspended = models.BooleanField(default=False, db_index=True)
    date_joined = models.DateTimeField(default=timezone.now)
    timezone = models.CharField(_('Time zone'), max_length=75,
                                choices=TIMEZONES, default='UTC')
    entries_per_page = models.IntegerField(_('Entries per page'), default=50,
                                           choices=ENTRIES_PER_PAGE)
    endless_pages = models.BooleanField(
        _('Endless pages'), default=True,
        help_text=_("Check this box if you'd like to use a 'load more' "
                    "button instead of the page links."))

    oldest_first = models.BooleanField(
        _('Oldest entries first'), default=False,
        help_text=_("Check this box if you'd like to have the oldest "
                    "entries appear first."))
    read_later = models.CharField(_('Read later service'), blank=True,
                                  choices=READ_LATER_SERVICES, max_length=50)
    read_later_credentials = models.TextField(_('Read later credentials'),
                                              blank=True)

    sharing_twitter = models.BooleanField(_('Enable tweet button'),
                                          default=False)
    sharing_gplus = models.BooleanField(_('Enable +1 button (Google+)'),
                                        default=False)
    sharing_email = models.BooleanField(_('Enable Mail button'), default=False)

    allow_media = models.BooleanField(_('Automatically allow external media'),
                                      default=False)

    font = models.CharField(
        _('Text font'), max_length=75, choices=FONTS, default=FONT_PT_SERIF,
        help_text=_('Non-system fonts are served by Google Web Fonts.'),
    )

    ttl = models.PositiveIntegerField(
        _('Retention days'), default=30,
        help_text=_('Number of days after which entries are deleted. The more '
                    'history you keep, the less snappy FeedHQ becomes. '
                    'Starred items are not deleted.'))
    es = models.NullBooleanField(default=True)

    objects = UserManager()

    class Meta:
        db_table = 'auth_user'

    def get_short_name(self):
        return self.username

    @property
    def last_update_key(self):
        return 'user:{0}:updates'.format(self.pk)

    @property
    def wallabag_url(self):
        return json.loads(self.read_later_credentials)['wallabag_url']

    @property
    def unread_count(self):
        if hasattr(self, '_unread_count'):
            return self._unread_count
        if self.es:
            return es.client.count(es.user_alias(self.pk),
                                   doc_type='entries',
                                   body={'query': {
                                       'term': {
                                           'read': False,
                                       }}})['count']
        else:
            return self.entries.unread()

    def last_updates(self):
        redis = get_redis_connection()
        values = redis.zrange(self.last_update_key, 0, 10**11, withscores=True)
        updates = {}
        for url, timestamp in values:
            updates[url.decode('utf-8')] = int(timestamp)
        return updates

    def refresh_updates(self):
        redis = get_redis_connection()
        last_updates = self.last_updates()
        urls = self.feeds.values_list('pk', 'url')
        for pk, url in urls:
            if url in last_updates:
                continue
            value = self.entries.filter(feed_id=pk).aggregate(
                date=Max('date'))['date']
            value = float(value.strftime('%s')) if value else 0
            redis.zadd(self.last_update_key, url, value)
        return self.last_updates()

    def ensure_alias(self):
        name = es.user_alias(self.pk)
        es.client.indices.put_alias(
            index=settings.ES_INDEX,
            name=name,
            body={
                'routing': self.pk,
                'filter': {'term': {'user': self.pk}},
            },
        )
        return name

    def save(self, *args, **kwargs):
        ret = super(User, self).save(*args, **kwargs)
        if self.es:
            self.ensure_alias()
        return ret

    def index_entries(self):
        if self.es:
            return
        name = self.ensure_alias()
        for feed in self.feeds.all():
            entries = feed.entries.all()
            docs = [doc.serialize() for doc in entries]
            if not docs:
                continue
            es.bulk(docs, index=name, timeout=60, raise_on_error=True)
        self.es = True
        self.save(update_fields=['es'])

    def delete_feed_entries(self, *pks):
        return es.client.delete_by_query(
            index=es.user_alias(self.pk),
            doc_type='entries',
            body={'query': {'filtered': {'filter': {'or': [
                {'term': {'feed': pk}} for pk in pks
            ]}}}},
        )

    def delete_category_entries(self, pk):
        return es.client.delete_by_query(
            index=es.user_alias(self.pk),
            doc_type='entries',
            body={'query': {'term': {'category': pk}}},
        )

    def delete_old(self):
        limit = timezone.now() - timedelta(days=self.ttl)
        if self.es:
            es.client.delete_by_query(
                index=es.user_alias(self.pk),
                doc_type='entries',
                body={'query': {'filtered': {
                    'filter': {'and': [
                        {'range': {'timestamp': {'lte': limit}}},
                        {'term': {'starred': False}},
                    ]},
                }}},
            )
        else:
            self.entries.filter(date__lte=limit).delete()

feedhq/profiles/templates/profiles/account_delete_done.html
{% extends "base.html" %}

{% block title %}{% trans "Good bye" %}{% endblock %}

{% block content %}
	<h2>{% trans "Good bye!" %}</h2>

	<p>{% trans "We hope you enjoyed using FeedHQ. Your account has successfully been deleted." %}</p>
{% endblock %}

feedhq/profiles/templates/profiles/account_delete_sent.html
{% extends "profiles/profile_base.html" %}

{% block title %}{% trans "Delete your account" %}{% endblock %}

{% block delete_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Verification email sent" %}</h2>
	<p>{% trans "Please check your email. You should receive an email to confirm your account deletion. Click on the link it contains to proceed." %}</p>
	<p>{% url "export" as dump_url %}{% blocktrans %}Before you go, you might be interested in a <a href="{{ dump_url }}">backup of your data</a>.{% endblocktrans %}</p>
{% endblock %}

feedhq/profiles/templates/profiles/bookmarklet.html
{% extends "profiles/profile_base.html" %}

{% block title %}{% trans "Subscribe button" %}{% endblock %}

{% block bookmarklet_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Subscribe button" %}</h2>

	<p>{% blocktrans %}FeedHQ provides a convenient way to subscribe to any site that provides feeds via <a target="_blank" href="https://www.subtome.com/">Subtome</a>. You need to <a target="_blank" href="https://www.subtome.com/settings.html">add the Subtome button</a> to your bookmarks toolbar or install the Chrome extension.{% endblocktrans %}</p>

	<p>{% trans "Next time you visit an interesting site, simply click on the subscribe button on your bookmarks toolbar. It'll let you easily add the new subscription to your FeedHQ account." %}</p>

	<iframe style="display:none;" src="https://www.subtome.com/register.html?name=FeedHQ&url={{ scheme }}://{{ site.domain }}{% url "feeds:subscribe" %}%3Ffeeds={feeds}%26url={url}"></iframe>
{% endblock %}

feedhq/profiles/templates/profiles/change_password.html
{% extends "profiles/profile_base.html" %}

{% block password_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Change your password" %}</h2>

	<form method="post" action="{% url "password" %}" id="password">
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Change password" %}">
			</div>
		</div>
	</form>
{% endblock %}

feedhq/profiles/templates/profiles/edit_profile.html
{% extends "profiles/profile_base.html" %}

{% block profile_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Edit your profile" %}</h2>

	<form method="post" action="{% url "profile" %}" id="profile">
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Update profile" %}">
			</div>
		</div>
	</form>
{% endblock %}

feedhq/profiles/templates/profiles/export.html
{% extends "profiles/profile_base.html" %}

{% block title %}{% trans "Export your subscriptions" %}{% endblock %}

{% block export_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Export your subscriptions" %}</h2>

	<p>{% trans "Subscriptions can be exported in a standard format. You can download them as an OPML file and import them back into another feed reader." %}</p>

	<p><a href="{% url "reader:subscription_export" %}">{% trans "Download OPML export" %}</a>.</p>
{% endblock %}

feedhq/profiles/templates/profiles/profile_base.html
{% extends "base.html" %}

{% block title %}{% trans "Account" %}{% endblock %}

{% block content %}
	<div class="profile-menu">
		<h1>{% trans "Account settings" %}</h1>
		<ul>
			<li><a class="{% block stats_selected %}{% endblock %}" href="{% url "stats" %}">{% trans "Stats" %}</a></li>
			<li><a class="{% block profile_selected %}{% endblock %}" href="{% url "profile" %}">{% trans "Profile" %}</a></li>
			<li><a class="{% block bookmarklet_selected %}{% endblock %}" href="{% url "bookmarklet" %}">{% trans "Subscribe button" %}</a></li>
			<li><a class="{% block sharing_selected %}{% endblock %}" href="{% url "sharing" %}">{% trans "Sharing" %}</a></li>
			<li><a class="{% block readlater_selected %}{% endblock %}" href="{% url "read_later" %}">{% trans "Read later" %}</a></li>
			<li><a class="{% block password_selected %}{% endblock %}" href="{% url "password" %}">{% trans "Password" %}</a></li>
			<li><a class="{% block export_selected %}{% endblock %}" href="{% url "export" %}">{% trans "Export" %}</a></li>
			<li><a class="{% block delete_selected %}{% endblock %}" href="{% url "destroy_account" %}">{% trans "Cancel your account" %}</a></li>
		</ul>
	</div>

	<div class="profile">
		{% block profile_content %}{% endblock %}
	</div>
{% endblock %}

feedhq/profiles/templates/profiles/read_later.html
{% extends "profiles/profile_base.html" %}

{% block title %}{% trans "Read later" %}{% endblock %}

{% block readlater_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Read later" %}</h2>

	{% if user.read_later %}
		<p>{% trans "Your current read-it-later service is:" %} <strong>{{ user.get_read_later_display }}</strong>.
		<a class="button" href="{% url "services" "none" %}">{% trans "Disable reading list management" %}</a></p>
	{% else %}
		<p>{% trans "You don't have any read-it-later service configured yet." %}</p>
	{% endif %}

	<p>{% trans "If you'd like to change that, select the service you want for reading list management:" %}</p>
	<ul>
		<li><a href="{% url "services" "readability" %}">Readability</a></li>
		<li><a href="{% url "services" "readitlater" %}">Read It Later</a></li>
		<li><a href="{% url "services" "instapaper" %}">Instapaper</a></li>
		<li><a href="{% url "services" "pocket" %}">Pocket</a></li>
		<li><a href="{% url "services" "wallabag" %}">Wallabag</a></li>
	</ul>
{% endblock %}

feedhq/profiles/templates/profiles/sharing.html
{% extends "profiles/profile_base.html" %}

{% block sharing_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Sharing preferences" %}</h2>

	<form method="post" action="{% url "sharing" %}" id="sharing">
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Update preferences" %}">
			</div>
		</div>
	</form>
{% endblock %}

feedhq/profiles/templates/profiles/user_confirm_delete.html
{% extends "profiles/profile_base.html" %}

{% block title %}{% trans "Delete your account" %}{% endblock %}

{% block delete_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Delete your account" %}</h2>
	<p>{% trans "You are about to delete your account. This can <strong>not</strong> be undone and will have immediate effect. Are you sure you want to do this?" %}</p>
	<p>{% url "export" as dump_url %}{% blocktrans %}Before you go, you might be interested in a <a href="{{ dump_url }}">backup of your data</a>.{% endblocktrans %}</p>
	<form method="post" action="{% url "destroy_confirm" view.token %}" id="delete">
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Delete my account now" %}">
				<a href="{% url "profile" %}">{% trans "Cancel" %}</a>
			</div>
		</div>
	</form>
{% endblock %}

feedhq/profiles/templates/profiles/user_detail.html
{% extends "profiles/profile_base.html" %}

{% block stats_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Stats" %}</h2>

	<p>{% blocktrans with since=user.date_joined|timesince %}You've been a FeedHQ user for <strong>{{ since }}</strong>.{% endblocktrans %}</p>

	<ul>
		<li>{% blocktrans count counter=categories %}{{ counter }} category{% plural %}{{ counter }} categories{% endblocktrans %}</li>
		<li>{% blocktrans count counter=feeds %}{{ counter }} feed{% plural %}{{ counter }} feeds{% endblocktrans %}</li>
		<li>{% blocktrans count counter=entries %}{{ counter }} entry{% plural %}{{ counter }} entries{% endblocktrans %}</li>
	</ul>
{% endblock %}

feedhq/profiles/templates/profiles/user_request_delete.html
{% extends "profiles/profile_base.html" %}

{% block title %}{% trans "Delete your account" %}{% endblock %}

{% block delete_selected %}current{% endblock %}

{% block profile_content %}
	<h2>{% trans "Delete your account" %}</h2>
	<p>{% trans "You are about to delete your account. It is a two-step process that requires an email verification for security reasons. Once deleted, you won't be able to recover your account." %}</p>
	<p>{% url "export" as dump_url %}{% blocktrans %}Before you go, you might be interested in a <a href="{{ dump_url }}">backup of your data</a>.{% endblocktrans %}</p>
	<form method="post" action="{% url "destroy_account" %}" id="delete">
		{% include "form.html" %}
		<div class="row">
			<div class="submit">
				<input type="submit" value="{% trans "Request account deletion" %}">
				<a href="{% url "profile" %}">{% trans "Cancel" %}</a>
			</div>
		</div>
	</form>
{% endblock %}